#ifndef __TK_STATUS_H__
#define __TK_STATUS_H__

typedef enum TKStatus {
	TK_OK = 0,
	TK_NAME_TOO_LONG,
	TK_FULL,
	TK_NULL,
    TK_BUSY,
    TK_CLOSED,
    TK_IOCTL_BAD_CODE,
    TK_IOCTL_IN_BUF_NULL,
    TK_IOCTL_IN_BUF_BAD_SIZE,
    TK_IOCTL_OUT_BUF_NULL,
    TK_IOCTL_OUT_BUF_BAD_SIZE,
    TK_POWER_STATES_UNSUPPORTED,
    TK_NO_POWER,
    TK_ALREADY_POWERED_ON,
    TK_ALREADY_POWERED_OFF,
    TK_UNEXPECTED
} TKStatus;

#endif
